server:
    port: 8080
    servlet:
      context-path: /gastos
spring:
    profiles: local
datasource:
    sampleapp:
      url: jdbc:h2:~/test
      username: SA
      password:
      driverClassName: org.h2.Driver
      defaultSchema:
      maxPoolSize: 10
      hibernate:
        hbm2ddl.method: create-drop
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
---

server:
    port: 8080
    servlet:
      context-path: /gastos
spring:
    profiles: prod, default
datasource:
    sampleapp:
      url: jdbc:mysql://localhost:3306/gastos
      username: root
      password: 106Galatea
      driverClassName: com.mysql.jdbc.Driver
      defaultSchema:
      maxPoolSize: 20
      hibernate:
        hbm2ddl.method: update
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect